controller_manager:
  ros__parameters:
    update_rate: 100 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    clearpath_velocity_controller:
      type: forward_command_controller/ForwardCommandController

clearpath_velocity_controller:
  ros__parameters:
    joints:
      - motor       
    interface_name: velocity